swagger: '2.0'
info:
  version: "1"
  title: "polypandaApi Documentation"
  description: polypandaApi is the api documentation for polypanda api service
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE
host: "dev.polypanda.io:8080"
basePath: /api/v1
schemes:
 - http

consumes:
- application/json
produces:
- application/json

paths:
  /panda:
    x-summary: Panda list
    get:
      summary: get list of pandas
      parameters:
        - name: pageNum
          in: query
          description: page of pandas to return
          type: integer
      responses:
        200:
          description: response ok
          schema:
            $ref: '#/definitions/RetPanda'
        202:
          description: Request is accepted but not gurantee to be executed
          schema:
            $ref: '#/definitions/RetSimple'
        400:
          $ref: '#/responses/BadRequest'
        401:
          $ref: '#/responses/Unauthorized'
        404:
          $ref: '#/responses/NotFound'

  /panda/{owner}/ownername:
    x-summary: ownername of owner
    put:
      summary: update ownername of a specific owner
      produces:
        - application/json
      parameters:
        - name: owner
          in: path
          description: owner address
          type: string
          required: true
        - name: name
          in: query
          description: new name for owner
          type: string
          required: true
      responses:
        200:
          description: response ok
          schema:
            $ref: '#/definitions/RetSimple'
        202:
          description: Request is accepted but not gurantee to be executed
          schema:
            $ref: '#/definitions/RetSimple'
        400:
          $ref: '#/responses/BadRequest'
        401:
          $ref: '#/responses/Unauthorized'
        404:
          $ref: '#/responses/NotFound'
  /panda/{index}/photo:
    x-summary: panda photo address
    put:
      summary: update photo address of a panda
      parameters:
        - name: index
          in: path
          description: index of a panda
          type: integer
          required: true
        - name: addr
          in: query
          description: photo address to be assigned to the panda
          type: string
          required: true
      responses:
        200:
          description: response ok
          schema:
            $ref: '#/definitions/RetSimple'
        202:
          description: Request is accepted but not gurantee to be executed
          schema:
            $ref: '#/definitions/RetSimple'
        400:
          $ref: '#/responses/BadRequest'
        401:
          $ref: '#/responses/Unauthorized'
        404:
          $ref: '#/responses/NotFound'
  /display/pagesize:
    x-summary: page size
    get: 
      summary: get page size
      responses:
        200: 
          description: response ok. page size is store in extra attribute
          schema:
            type: object
            properties:
              code:
                type : integer
              message:
                type: string
              extra:
                type: string
              extraCode:
                type: integer
            required:
              - code
              - message
              - extra
        202:
          description: Request is accepted but not gurantee to be executed
          schema:
            $ref: '#/definitions/RetSimple'
        400:
          $ref: '#/responses/BadRequest'
        401:
          $ref: '#/responses/Unauthorized'
        404:
          $ref: '#/responses/NotFound'
    put:
      summary: set page size
      parameters:
        - name: size
          in: query
          description: number of pandas in a page
          type: integer
          required: true
      responses:
        200:
          description: response ok
          schema:
            $ref: '#/definitions/RetSimple'
        202:
          description: Request is accepted but not gurantee to be executed
          schema:
            $ref: '#/definitions/RetSimple'
        400:
          $ref: '#/responses/BadRequest'
        401:
          $ref: '#/responses/Unauthorized'
        404:
          $ref: '#/responses/NotFound'
             

definitions:
  RetSimple:
    title: RetSimple
    type: object
    properties:
      code:
        type : integer
      message:
        type: string
      extra:
        type: string
      extraCode:
        type: integer
    required:
      - code
      - message
    example:
      code: 404
      message: "fail code 404"
      extra: 
      extraCode: 0
  RetPanda:
    title: RetPanda
    type: object
    properties:
      code:
        type : integer
      message:
        type: string
      extra:
        type: string
      extraCode:
        type: integer
      pandas:
        type: array
        items:
          $ref: '#/definitions/Panda'
    required:
      - code
      - message
    example:
      code: 200
      message: "200 OK"
      extra: ""
      extraCode: 0
      pandas:
        - pandaIndex: 0
          genes: "MDhmZTQxMTRlMDlkYTkyODJjY2Q4ZjY0NDExYTRiNTI="
          birthTime: 1523031825
          coolDown: 1800
          rank: 0
          motherID: 0
          fatherID: 0
          generation: 0
          owner: "NGUyODI4MGIwZTZhNDA1ZjU0MjI="
          ownerName: "divine-frog"
          photoURL: "localofphoto"
          snapURL:
        - pandaIndex: 1
          genes: "MjQ1NjRmNzZmMjcxMGQxMDI2MWE2N2FlNTc3MGUxNzc="
          birthTime: 1523031825
          coolDown: 172800
          rank: 0
          motherID: 0
          fatherID: 0
          generation: 0
          owner: "NjQyOTZlM2IyNDM0MTAyNDFlMjY="
          ownerName: "frosty-butterfly"
          photoURL: "localofphoto"
          snapURL:
    
  Panda:
    title: Panda
    type: object
    properties:
      pandaIndex:
        type: integer
      genes:
        type: string
      birthTime:
        type: integer
      coolDown:
        type: integer 
      rank:
        type: integer
      motherID:
        type: integer
      fatherID:
        type: integer
      generation:
        type: integer
      owner:
        type: string
      ownerName:
        type: string
      photoURL:
        type: string
      snapURL:
        type: string
    example:
      pandaIndex: 0
      genes: "MDhmZTQxMTRlMDlkYTkyODJjY2Q4ZjY0NDExYTRiNTI="
      birthTime: 1523031825
      coolDown: 1800
      rank: 0
      motherID: 0
      fatherID: 0
      generation: 0
      owner: "NGUyODI4MGIwZTZhNDA1ZjU0MjI="
      ownerName: "divine-frog"
      photoURL: "localofphoto"
      snapURL:
    
  
 # Descriptions of common responses
responses:
  BadRequest:
    description: User request is invalid
    schema:
      $ref: "#/definitions/RetSimple"
  NotFound:
    description: The specified resource was not found
    schema:
      $ref: "#/definitions/RetSimple"
  Unauthorized:
    description: Unauthorized
    schema:
      $ref: "#/definitions/RetSimple"
